import type {
  AnalyticsInsight,
  DauMauAnalytics,
  EngagementAnalyticsResponse,
  InteractionAnalytics,
  InteractionBreakdownItem,
} from "../types";

/** Shared thresholds — aligned with DauMauAnalytics, InteractionAnalytics, and backend StatsAdminServiceImpl. */
export const INSIGHT_THRESHOLDS = {
  MIN_RELIABLE_MAU: 20,
  DAU_GROWTH_STABLE_MIN: -5,
  DAU_GROWTH_STABLE_MAX: 5,
  DAU_GROWTH_SOFT_MAX: 20,
  DAU_GROWTH_STRONG_MIN: -20,
  INTERACTION_GROWTH_STRONG_UP: 20,
  INTERACTION_GROWTH_LIGHT_UP: 5,
  INTERACTION_GROWTH_STABLE_MIN: -5,
  INTERACTION_GROWTH_LIGHT_DOWN: -20,
  INTERACTION_DROP_PCT: -30,
  DOMINANT_INTERACTION_PCT: 40,
  PEAK_SPIKE_MULTIPLIER: 2,
  CONSECUTIVE_DAU_DROP_DAYS: 3,
  POST_LOW_PCT: 25,
} as const;

export type InsightLevel = AnalyticsInsight["level"];
export type SeverityLabel = "tốt" | "cần chú ý" | "cảnh báo" | "thông tin";

export interface AutoGeneratedInsight {
  id: string;
  message: string;
  level: InsightLevel;
  severityLabel: SeverityLabel;
}

export const SEVERITY_BY_LEVEL: Record<InsightLevel, SeverityLabel> = {
  success: "tốt",
  warning: "cần chú ý",
  danger: "cảnh báo",
  info: "thông tin",
};

const fmtOneDecimal = new Intl.NumberFormat("vi-VN", {
  minimumFractionDigits: 1,
  maximumFractionDigits: 1,
});
const fmtInt = new Intl.NumberFormat("vi-VN");

function formatRate(rate: number | null): string {
  if (rate == null) return "—";
  return fmtOneDecimal.format(Math.abs(rate));
}

function formatPeakDay(date: string | null, chartLabel?: string): string {
  if (chartLabel) return chartLabel;
  if (!date) return "—";
  const d = new Date(date);
  return d.toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit" });
}

function classifyDauInsightLevel(growthRate: number | null, lowData: boolean): InsightLevel {
  if (lowData) return "info";
  if (growthRate == null) return "info";
  if (growthRate <= INSIGHT_THRESHOLDS.DAU_GROWTH_STRONG_MIN) return "danger";
  if (growthRate < INSIGHT_THRESHOLDS.DAU_GROWTH_STABLE_MIN) return "warning";
  if (growthRate > INSIGHT_THRESHOLDS.DAU_GROWTH_SOFT_MAX) return "success";
  if (growthRate > INSIGHT_THRESHOLDS.DAU_GROWTH_STABLE_MAX) return "success";
  return "success";
}

function buildDauTrendMessage(growthRate: number | null, trendStatus: string): string {
  if (growthRate == null) {
    return `DAU ${trendStatus.toLowerCase()} — chưa có dữ liệu so sánh kỳ trước.`;
  }
  const rate = formatRate(growthRate);
  if (growthRate >= INSIGHT_THRESHOLDS.DAU_GROWTH_STABLE_MIN && growthRate <= INSIGHT_THRESHOLDS.DAU_GROWTH_STABLE_MAX) {
    const direction = growthRate >= 0 ? "tăng" : "giảm";
    return `DAU ổn định, ${direction} ${rate}% so với kỳ trước.`;
  }
  if (growthRate > INSIGHT_THRESHOLDS.DAU_GROWTH_STABLE_MAX) {
    const qualifier = growthRate > INSIGHT_THRESHOLDS.DAU_GROWTH_SOFT_MAX ? "tăng mạnh" : "tăng";
    return `DAU ${qualifier} ${rate}% so với kỳ trước.`;
  }
  const qualifier = growthRate < INSIGHT_THRESHOLDS.DAU_GROWTH_STRONG_MIN ? "giảm mạnh" : "giảm";
  return `DAU ${qualifier} ${rate}% so với kỳ trước.`;
}

function classifyInteractionInsightLevel(growthRate: number | null, lowData: boolean): InsightLevel {
  if (lowData) return "info";
  if (growthRate == null) return "info";
  if (growthRate <= INSIGHT_THRESHOLDS.INTERACTION_GROWTH_LIGHT_DOWN) return "danger";
  if (growthRate < INSIGHT_THRESHOLDS.INTERACTION_GROWTH_STABLE_MIN) return "warning";
  if (growthRate > INSIGHT_THRESHOLDS.INTERACTION_GROWTH_STRONG_UP) return "success";
  return "success";
}

function buildInteractionTrendMessage(growthRate: number | null): string {
  if (growthRate == null) {
    return "Tổng tương tác ổn định — chưa có dữ liệu so sánh kỳ trước.";
  }
  const rate = formatRate(growthRate);
  if (growthRate > INSIGHT_THRESHOLDS.INTERACTION_GROWTH_STRONG_UP) {
    return `Tổng tương tác tăng mạnh ${rate}%.`;
  }
  if (growthRate > INSIGHT_THRESHOLDS.INTERACTION_GROWTH_LIGHT_UP) {
    return `Tổng tương tác tăng nhẹ ${rate}%.`;
  }
  if (growthRate >= INSIGHT_THRESHOLDS.INTERACTION_GROWTH_STABLE_MIN) {
    return `Tổng tương tác ổn định (${growthRate >= 0 ? "+" : "-"}${rate}% so với kỳ trước).`;
  }
  if (growthRate >= INSIGHT_THRESHOLDS.INTERACTION_GROWTH_LIGHT_DOWN) {
    return `Tổng tương tác giảm nhẹ ${rate}%.`;
  }
  return `Tổng tương tác giảm mạnh ${rate}%.`;
}

function getTopBreakdownItem(breakdown: InteractionBreakdownItem[]): InteractionBreakdownItem | null {
  if (breakdown.length === 0) return null;
  return breakdown.reduce((top, item) => (item.count > top.count ? item : top), breakdown[0]);
}

function collectAnomalySigns(
  dau: DauMauAnalytics | null | undefined,
  interactions: InteractionAnalytics | null | undefined,
  lowData: boolean,
): string[] {
  const signs: string[] = [];
  const dauSummary = dau?.summary;
  const interactionSummary = interactions?.summary;

  if (lowData) {
    signs.push(`MAU dưới ${INSIGHT_THRESHOLDS.MIN_RELIABLE_MAU} — mẫu chưa đủ tin cậy`);
  }
  if ((dauSummary?.consecutiveDauDropDays ?? 0) >= INSIGHT_THRESHOLDS.CONSECUTIVE_DAU_DROP_DAYS) {
    signs.push(`DAU giảm ${dauSummary!.consecutiveDauDropDays} ngày liên tiếp`);
  }
  if (dauSummary?.dauTrendStatus === "Không ổn định" || dauSummary?.dauTrendStatus === "Giảm cuối kỳ") {
    signs.push(`Xu hướng DAU: ${dauSummary.dauTrendStatus.toLowerCase()}`);
  }
  if (interactionSummary?.interactionTrendStatus === "Không ổn định") {
    signs.push("Biến động tương tác theo ngày bất thường");
  }
  if (
    interactionSummary?.interactionGrowthRate != null
    && interactionSummary.interactionGrowthRate <= INSIGHT_THRESHOLDS.INTERACTION_DROP_PCT
  ) {
    signs.push(`Tương tác giảm ${formatRate(interactionSummary.interactionGrowthRate)}% so với kỳ trước`);
  }
  const avg = interactionSummary?.averageInteractionsPerDay ?? 0;
  const peak = interactionSummary?.peakInteractionCount ?? 0;
  if (avg > 0 && peak >= avg * INSIGHT_THRESHOLDS.PEAK_SPIKE_MULTIPLIER) {
    signs.push(`Đỉnh tương tác gấp ${fmtOneDecimal.format(peak / avg)} lần trung bình/ngày`);
  }
  const top = getTopBreakdownItem(interactions?.breakdown ?? []);
  if (top && top.percentage >= INSIGHT_THRESHOLDS.DOMINANT_INTERACTION_PCT) {
    signs.push(`${top.type} chiếm ${top.percentage}% — lệch cơ cấu tương tác`);
  }

  return signs;
}

function classifyAnomalyLevel(
  signs: string[],
  lowData: boolean,
  dau: DauMauAnalytics | null | undefined,
  interactions: InteractionAnalytics | null | undefined,
): InsightLevel {
  if (signs.length === 0) return "success";
  const consecutiveDrop = dau?.summary?.consecutiveDauDropDays ?? 0;
  const interactionGrowth = interactions?.summary?.interactionGrowthRate;
  if (
    consecutiveDrop >= INSIGHT_THRESHOLDS.CONSECUTIVE_DAU_DROP_DAYS
    || (interactionGrowth != null && interactionGrowth <= INSIGHT_THRESHOLDS.INTERACTION_DROP_PCT)
  ) {
    return "danger";
  }
  return "warning";
}

function buildAnomalyMessage(signs: string[]): string {
  if (signs.length === 0) {
    return "Chưa phát hiện dấu hiệu bất thường trong kỳ này.";
  }
  if (signs.length === 1) {
    return `Có dấu hiệu bất thường: ${signs[0]}.`;
  }
  return `Có ${signs.length} dấu hiệu bất thường: ${signs.join("; ")}.`;
}

function buildRecommendedAction(
  dau: DauMauAnalytics | null | undefined,
  interactions: InteractionAnalytics | null | undefined,
  lowData: boolean,
): { message: string; level: InsightLevel } {
  const breakdown = interactions?.breakdown ?? [];
  const posts = breakdown.find((b) => b.type === "Bài đăng");
  const postsPct = posts?.percentage ?? 0;
  const postsCount = posts?.count ?? 0;
  const comments = breakdown.find((b) => b.type === "Bình luận")?.count ?? 0;
  const reactions = breakdown.find((b) => b.type === "Cảm xúc")?.count ?? 0;
  const dauSummary = dau?.summary;
  const interactionSummary = interactions?.summary;
  const interactionGrowth = interactionSummary?.interactionGrowthRate ?? null;

  if (lowData) {
    return {
      message: "Tiếp tục thu thập dữ liệu trước khi đưa ra quyết định vận hành.",
      level: "info",
    };
  }
  if ((interactionSummary?.totalInteractions ?? 0) === 0) {
    return {
      message: "Khuyến khích người dùng đăng bài, bình luận hoặc phản ứng.",
      level: "warning",
    };
  }
  if (
    postsPct > 0
    && postsPct < INSIGHT_THRESHOLDS.POST_LOW_PCT
    && (comments + reactions) > postsCount
  ) {
    return {
      message: `Bài đăng chỉ ${postsPct}% — nên khuyến khích người dùng tạo nội dung.`,
      level: "warning",
    };
  }
  if ((dauSummary?.consecutiveDauDropDays ?? 0) >= INSIGHT_THRESHOLDS.CONSECUTIVE_DAU_DROP_DAYS) {
    return {
      message: "Kiểm tra push notification, nội dung mới và lỗi hệ thống để phục hồi DAU.",
      level: "danger",
    };
  }
  if (interactionGrowth != null && interactionGrowth <= INSIGHT_THRESHOLDS.INTERACTION_DROP_PCT) {
    return {
      message: "Rà soát lỗi hệ thống và nội dung mới, cân nhắc push notification.",
      level: "danger",
    };
  }
  const avg = interactionSummary?.averageInteractionsPerDay ?? 0;
  const peak = interactionSummary?.peakInteractionCount ?? 0;
  if (avg > 0 && peak >= avg * INSIGHT_THRESHOLDS.PEAK_SPIKE_MULTIPLIER) {
    return {
      message: "Xem xét nội dung/sự kiện ngày đỉnh để nhân rộng mô hình thành công.",
      level: "info",
    };
  }
  const top = getTopBreakdownItem(breakdown);
  if (top && top.percentage >= INSIGHT_THRESHOLDS.DOMINANT_INTERACTION_PCT && top.type !== "Bài đăng") {
    return {
      message: `Tạo thêm nội dung gợi ý — ${top.type} đang chiếm ${top.percentage}% tổng tương tác.`,
      level: "info",
    };
  }
  if (interactionGrowth != null && interactionGrowth > INSIGHT_THRESHOLDS.INTERACTION_GROWTH_STRONG_UP) {
    return {
      message: "Duy trì chiến lược nội dung hiện tại và theo dõi ngày đỉnh.",
      level: "success",
    };
  }
  return {
    message: "Tiếp tục theo dõi chỉ số — chưa cần can thiệp khẩn.",
    level: "success",
  };
}

function wrapInsight(id: string, message: string, level: InsightLevel): AutoGeneratedInsight {
  return { id, message, level, severityLabel: SEVERITY_BY_LEVEL[level] };
}

export function generateAutoInsights(
  data: EngagementAnalyticsResponse | null,
  lowData: boolean,
): AutoGeneratedInsight[] {
  if (!data) return [];

  const dau = data.dauMau;
  const interactions = data.interactions;
  const dauSummary = dau.summary;
  const interactionSummary = interactions.summary;
  const top = getTopBreakdownItem(interactions.breakdown);

  const peakLabel = interactions.chartData.find(
    (p) => p.date === interactionSummary.peakInteractionDay,
  )?.label;

  const anomalySigns = collectAnomalySigns(dau, interactions, lowData);
  const action = buildRecommendedAction(dau, interactions, lowData);

  const insights: AutoGeneratedInsight[] = [
    wrapInsight(
      "dau-trend",
      buildDauTrendMessage(dauSummary.dauGrowthRate, dauSummary.dauTrendStatus),
      classifyDauInsightLevel(dauSummary.dauGrowthRate, lowData),
    ),
    wrapInsight(
      "interaction-trend",
      buildInteractionTrendMessage(interactionSummary.interactionGrowthRate),
      classifyInteractionInsightLevel(interactionSummary.interactionGrowthRate, lowData),
    ),
    wrapInsight(
      "top-type",
      top && top.count > 0
        ? `${top.type} chiếm cao nhất ${top.percentage}%.`
        : "Chưa có loại tương tác nổi bật trong kỳ.",
      top && top.percentage >= INSIGHT_THRESHOLDS.DOMINANT_INTERACTION_PCT ? "info" : "success",
    ),
    wrapInsight(
      "peak-day",
      interactionSummary.peakInteractionDay
        ? `${formatPeakDay(interactionSummary.peakInteractionDay, peakLabel)} có tương tác cao nhất ${fmtInt.format(interactionSummary.peakInteractionCount)} lượt.`
        : "Chưa xác định ngày đỉnh tương tác trong kỳ.",
      interactionSummary.peakInteractionCount > 0 ? "success" : "info",
    ),
    wrapInsight(
      "anomaly",
      buildAnomalyMessage(anomalySigns),
      classifyAnomalyLevel(anomalySigns, lowData, dau, interactions),
    ),
    wrapInsight("action", `Đề xuất: ${action.message}`, action.level),
  ];

  return insights;
}
