import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { generateAutoInsights } from "../lib/generateAutoInsights";
import type { EngagementAnalyticsResponse } from "../types";
import type { AutoGeneratedInsight, InsightLevel } from "../lib/generateAutoInsights";

const SEVERITY_BADGE: Record<InsightLevel, string> = {
  success: "bg-emerald-100 text-emerald-800 hover:bg-emerald-100 dark:bg-emerald-950 dark:text-emerald-300",
  warning: "bg-amber-100 text-amber-800 hover:bg-amber-100 dark:bg-amber-950 dark:text-amber-300",
  danger: "bg-red-100 text-red-800 hover:bg-red-100 dark:bg-red-950 dark:text-red-300",
  info: "bg-blue-100 text-blue-800 hover:bg-blue-100 dark:bg-blue-950 dark:text-blue-300",
};

interface AutoInsightsSectionProps {
  data: EngagementAnalyticsResponse | null;
  loading: boolean;
  lowData: boolean;
}

export const AutoInsightsSection = ({ data, loading, lowData }: AutoInsightsSectionProps) => {
  const insights = loading ? [] : generateAutoInsights(data, lowData);

  return (
    <section className="space-y-3">
      <div>
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-violet-500" />
          <h2 className="text-sm font-semibold text-foreground">Nhận xét tự động</h2>
        </div>
        <p className="text-xs text-muted-foreground mt-0.5">
          Tóm tắt nhanh từ dữ liệu DAU và tương tác trong kỳ đang xem.
        </p>
      </div>

      <Card>
        <CardContent className="pt-4 pb-3">
          {loading ? (
            <div className="space-y-2">
              {[1, 2, 3, 4, 5, 6].map((i) => (
                <Skeleton key={i} className="h-9 w-full rounded-md" />
              ))}
            </div>
          ) : insights.length === 0 ? (
            <p className="text-sm text-muted-foreground">Chưa có dữ liệu để tạo nhận xét.</p>
          ) : (
            <ul className="space-y-2">
              {insights.map((insight) => (
                <InsightRow key={insight.id} insight={insight} />
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </section>
  );
};

const InsightRow = ({ insight }: { insight: AutoGeneratedInsight }) => (
  <li className="flex items-start gap-2.5 rounded-md border border-border/60 bg-muted/20 px-3 py-2">
    <Badge
      variant="secondary"
      className={`mt-0.5 shrink-0 text-[10px] font-semibold uppercase tracking-wide ${SEVERITY_BADGE[insight.level]}`}
    >
      {insight.severityLabel}
    </Badge>
    <p className="text-sm leading-snug text-foreground">{insight.message}</p>
  </li>
);

export default AutoInsightsSection;
