package project.kconnecta.admin.backend.feature.stats.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import project.kconnecta.admin.backend.feature.stats.dto.response.*;

import java.util.*;

@Slf4j
@Service
@RequiredArgsConstructor
public class GeminiStatsService {

    private static final String GEMINI_URL =
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent";

    @Value("${gemini.api-key:}")
    private String apiKey;

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;

    public List<AutoGeneratedInsightDto> getAutoInsights(
            DauMauSummary dauSummary,
            InteractionSummary interactionSummary,
            List<InteractionBreakdownItem> breakdown) {

        if (apiKey == null || apiKey.isBlank()) {
            log.warn("Gemini API key not configured, falling back to local auto-insights generation");
            return generateFallbackInsights(dauSummary, interactionSummary, breakdown);
        }

        try {
            // Build breakdown string
            StringBuilder breakdownSb = new StringBuilder();
            for (InteractionBreakdownItem item : breakdown) {
                breakdownSb.append(String.format("%s: %d (%d%%); ", item.getType(), item.getCount(), item.getPercentage()));
            }

            String prompt = String.format("""
                Bạn là một chuyên gia phân tích dữ liệu hệ thống. Hãy phân tích các số liệu thống kê hoạt động (DAU/MAU) và tương tác người dùng dưới đây, sau đó đưa ra chính xác 6 nhận xét tự động theo định dạng JSON được yêu cầu.

                Dữ liệu thống kê:
                - DAU hôm nay: %d
                - MAU 30 ngày: %d
                - Tỉ lệ DAU/MAU: %.1f%%
                - DAU trung bình: %.1f
                - Tỉ lệ tăng trưởng DAU so với kỳ trước: %s%%
                - Trạng thái xu hướng DAU: %s
                - Tổng lượt tương tác trong kỳ: %d
                - Tỉ lệ tăng trưởng tương tác so với kỳ trước: %s%%
                - Trạng thái xu hướng tương tác: %s
                - Phân bổ tương tác theo loại: %s
                - Ngày đỉnh tương tác: %s (với %d lượt tương tác)
                - Số ngày DAU giảm liên tiếp: %d ngày

                Hãy tạo ra đúng 6 nhận xét tương ứng với 6 ID sau:
                1. "dau-trend": Phân tích xu hướng DAU (tăng/giảm/ổn định và tỉ lệ).
                2. "interaction-trend": Phân tích xu hướng tổng tương tác (tăng/giảm/ổn định và tỉ lệ).
                3. "top-type": Chỉ ra loại tương tác chiếm tỷ lệ cao nhất và tỷ lệ của nó.
                4. "peak-day": Nhận xét về ngày có lượng tương tác cao nhất.
                5. "anomaly": Phát hiện bất thường (ví dụ: DAU giảm liên tiếp, lệch cơ cấu tương tác, hoặc ghi "Chưa phát hiện dấu hiệu bất thường trong kỳ này" nếu mọi thứ ổn định).
                6. "action": Đề xuất hành động cụ thể để cải thiện tương tác hoặc duy trì hệ thống (tiền tố bắt buộc là "Đề xuất: ...").

                Mỗi nhận xét phải chứa các trường:
                - "id": Trùng với 1 trong 6 ID trên.
                - "message": Nội dung nhận xét bằng tiếng Việt, ngắn gọn, súc tích (1 câu).
                - "level": Mức độ nghiêm trọng, chọn 1 trong 4 giá trị sau: "success" (tốt), "warning" (cần chú ý), "danger" (cảnh báo), "info" (thông tin).
                - "severityLabel": nhãn hiển thị tương ứng với "level" ("tốt", "cần chú ý", "cảnh báo", "thông tin").

                Trả về kết quả dưới dạng một mảng JSON hợp lệ chứa đúng 6 đối tượng này. Không viết thêm bất kỳ văn bản giải thích hay khối ```json...``` nào khác ngoài chuỗi JSON này.
                """,
                dauSummary.getDauToday(),
                dauSummary.getMau30Days(),
                dauSummary.getDauMauRatio(),
                dauSummary.getAverageDau30Days(),
                dauSummary.getDauGrowthRate() != null ? String.format("%.1f", dauSummary.getDauGrowthRate()) : "chưa có số liệu",
                dauSummary.getDauTrendStatus(),
                interactionSummary.getTotalInteractions(),
                interactionSummary.getInteractionGrowthRate() != null ? String.format("%.1f", interactionSummary.getInteractionGrowthRate()) : "chưa có số liệu",
                interactionSummary.getInteractionTrendStatus(),
                breakdownSb.toString(),
                interactionSummary.getPeakInteractionDay() != null ? interactionSummary.getPeakInteractionDay() : "chưa có số liệu",
                interactionSummary.getPeakInteractionCount(),
                dauSummary.getConsecutiveDauDropDays()
            );

            Map<String, Object> body = Map.of(
                    "contents", List.of(Map.of("parts", List.of(Map.of("text", prompt))))
            );

            org.springframework.http.HttpHeaders headers = new org.springframework.http.HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            String bodyStr = objectMapper.writeValueAsString(body);

            var entity = new org.springframework.http.HttpEntity<>(bodyStr, headers);
            var resp = restTemplate.exchange(
                    GEMINI_URL + "?key=" + apiKey,
                    org.springframework.http.HttpMethod.POST,
                    entity,
                    String.class);

            if (resp.getBody() == null) {
                log.warn("Empty response from Gemini, falling back to local auto-insights");
                return generateFallbackInsights(dauSummary, interactionSummary, breakdown);
            }

            JsonNode root = objectMapper.readTree(resp.getBody());
            String text = root.path("candidates").path(0).path("content").path("parts").path(0).path("text").asText();

            text = text.trim();
            if (text.startsWith("```")) {
                int firstLineBreak = text.indexOf('\n');
                int lastBackticks = text.lastIndexOf("```");
                if (firstLineBreak != -1 && lastBackticks > firstLineBreak) {
                    text = text.substring(firstLineBreak + 1, lastBackticks).trim();
                }
            }

            List<AutoGeneratedInsightDto> insights = objectMapper.readValue(text, new TypeReference<List<AutoGeneratedInsightDto>>() {});
            if (insights == null || insights.isEmpty()) {
                throw new IllegalStateException("Failed to parse insights from Gemini response");
            }
            return insights;

        } catch (Exception e) {
            log.error("Error calling Gemini API, falling back to local auto-insights: ", e);
            return generateFallbackInsights(dauSummary, interactionSummary, breakdown);
        }
    }

    private List<AutoGeneratedInsightDto> generateFallbackInsights(
            DauMauSummary dauSummary,
            InteractionSummary interactionSummary,
            List<InteractionBreakdownItem> breakdown) {

        List<AutoGeneratedInsightDto> insights = new ArrayList<>();
        boolean lowData = dauSummary.getMau30Days() < 20;

        // 1. DAU Trend
        String dauMessage;
        String dauLevel = "success";
        Double dauGrowth = dauSummary.getDauGrowthRate();
        if (dauGrowth == null) {
            dauMessage = String.format("DAU %s — chưa có dữ liệu so sánh kỳ trước.", dauSummary.getDauTrendStatus().toLowerCase());
            dauLevel = "info";
        } else {
            String rateStr = String.format("%.1f", Math.abs(dauGrowth));
            if (dauGrowth >= -5.0 && dauGrowth <= 5.0) {
                String dir = dauGrowth >= 0 ? "tăng" : "giảm";
                dauMessage = String.format("DAU ổn định, %s %s%% so với kỳ trước.", dir, rateStr);
            } else if (dauGrowth > 5.0) {
                String qualifier = dauGrowth > 20.0 ? "tăng mạnh" : "tăng";
                dauMessage = String.format("DAU %s %s%% so với kỳ trước.", qualifier, rateStr);
            } else {
                String qualifier = dauGrowth < -20.0 ? "giảm mạnh" : "giảm";
                dauMessage = String.format("DAU %s %s%% so với kỳ trước.", qualifier, rateStr);
                dauLevel = dauGrowth < -20.0 ? "danger" : "warning";
            }
        }
        insights.add(AutoGeneratedInsightDto.builder()
                .id("dau-trend")
                .message(dauMessage)
                .level(dauLevel)
                .severityLabel(getSeverityLabel(dauLevel))
                .build());

        // 2. Interaction Trend
        String intMessage;
        String intLevel = "success";
        Double intGrowth = interactionSummary.getInteractionGrowthRate();
        if (intGrowth == null) {
            intMessage = "Tổng tương tác ổn định — chưa có dữ liệu so sánh kỳ trước.";
            intLevel = "info";
        } else {
            String rateStr = String.format("%.1f", Math.abs(intGrowth));
            if (intGrowth > 20.0) {
                intMessage = String.format("Tổng tương tác tăng mạnh %s%%.", rateStr);
            } else if (intGrowth > 5.0) {
                intMessage = String.format("Tổng tương tác tăng nhẹ %s%%.", rateStr);
            } else if (intGrowth >= -5.0) {
                String sign = intGrowth >= 0 ? "+" : "-";
                intMessage = String.format("Tổng tương tác ổn định (%s%s%% so với kỳ trước).", sign, rateStr);
            } else if (intGrowth >= -20.0) {
                intMessage = String.format("Tổng tương tác giảm nhẹ %s%%.", rateStr);
                intLevel = "warning";
            } else {
                intMessage = String.format("Tổng tương tác giảm mạnh %s%%.", rateStr);
                intLevel = "danger";
            }
        }
        insights.add(AutoGeneratedInsightDto.builder()
                .id("interaction-trend")
                .message(intMessage)
                .level(intLevel)
                .severityLabel(getSeverityLabel(intLevel))
                .build());

        // 3. Top Type
        InteractionBreakdownItem top = breakdown.stream()
                .max(Comparator.comparingLong(InteractionBreakdownItem::getCount))
                .orElse(null);
        String topMessage;
        String topLevel = "success";
        if (top != null && top.getCount() > 0) {
            topMessage = String.format("%s chiếm cao nhất %d%%.", top.getType(), top.getPercentage());
            if (top.getPercentage() >= 40.0) {
                topLevel = "info";
            }
        } else {
            topMessage = "Chưa có loại tương tác nổi bật trong kỳ.";
            topLevel = "info";
        }
        insights.add(AutoGeneratedInsightDto.builder()
                .id("top-type")
                .message(topMessage)
                .level(topLevel)
                .severityLabel(getSeverityLabel(topLevel))
                .build());

        // 4. Peak Day
        String peakMessage;
        String peakLevel = "success";
        if (interactionSummary.getPeakInteractionDay() != null) {
            String dateLabel = interactionSummary.getPeakInteractionDay();
            peakMessage = String.format("%s có tương tác cao nhất %,d lượt.", dateLabel, interactionSummary.getPeakInteractionCount());
        } else {
            peakMessage = "Chưa xác định ngày đỉnh tương tác trong kỳ.";
            peakLevel = "info";
        }
        insights.add(AutoGeneratedInsightDto.builder()
                .id("peak-day")
                .message(peakMessage)
                .level(peakLevel)
                .severityLabel(getSeverityLabel(peakLevel))
                .build());

        // 5. Anomaly Signs
        List<String> anomalySigns = new ArrayList<>();
        if (lowData) {
            anomalySigns.add("MAU dưới 20 — mẫu chưa đủ tin cậy");
        }
        if (dauSummary.getConsecutiveDauDropDays() >= 3) {
            anomalySigns.add(String.format("DAU giảm %d ngày liên tiếp", dauSummary.getConsecutiveDauDropDays()));
        }
        if ("Không ổn định".equals(dauSummary.getDauTrendStatus()) || "Giảm cuối kỳ".equals(dauSummary.getDauTrendStatus())) {
            anomalySigns.add(String.format("Xu hướng DAU: %s", dauSummary.getDauTrendStatus().toLowerCase()));
        }
        if ("Không ổn định".equals(interactionSummary.getInteractionTrendStatus())) {
            anomalySigns.add("Biến động tương tác theo ngày bất thường");
        }
        if (intGrowth != null && intGrowth <= -30.0) {
            anomalySigns.add(String.format("Tương tác giảm %.1f%% so với kỳ trước", Math.abs(intGrowth)));
        }
        double avg = interactionSummary.getAverageInteractionsPerDay();
        long peak = interactionSummary.getPeakInteractionCount();
        if (avg > 0 && peak >= avg * 2.0) {
            anomalySigns.add(String.format("Đỉnh tương tác gấp %.1f lần trung bình/ngày", (double) peak / avg));
        }
        if (top != null && top.getPercentage() >= 40.0) {
            anomalySigns.add(String.format("%s chiếm %d%% — lệch cơ cấu tương tác", top.getType(), top.getPercentage()));
        }

        String anomalyMessage;
        String anomalyLevel = "success";
        if (anomalySigns.isEmpty()) {
            anomalyMessage = "Chưa phát hiện dấu hiệu bất thường trong kỳ này.";
        } else {
            anomalyLevel = (dauSummary.getConsecutiveDauDropDays() >= 3 || (intGrowth != null && intGrowth <= -30.0)) ? "danger" : "warning";
            if (anomalySigns.size() == 1) {
                anomalyMessage = "Có dấu hiệu bất thường: " + anomalySigns.get(0) + ".";
            } else {
                anomalyMessage = String.format("Có %d dấu hiệu bất thường: %s.", anomalySigns.size(), String.join("; ", anomalySigns));
            }
        }
        insights.add(AutoGeneratedInsightDto.builder()
                .id("anomaly")
                .message(anomalyMessage)
                .level(anomalyLevel)
                .severityLabel(getSeverityLabel(anomalyLevel))
                .build());

        // 6. Recommended Action
        String actionMsg;
        String actionLevel = "success";
        InteractionBreakdownItem postsItem = breakdown.stream().filter(b -> "Bài đăng".equals(b.getType())).findFirst().orElse(null);
        double postsPct = postsItem != null ? postsItem.getPercentage() : 0.0;
        long postsCount = postsItem != null ? postsItem.getCount() : 0L;
        long commentsCount = breakdown.stream().filter(b -> "Bình luận".equals(b.getType())).mapToLong(InteractionBreakdownItem::getCount).sum();
        long reactionsCount = breakdown.stream().filter(b -> "Cảm xúc".equals(b.getType())).mapToLong(InteractionBreakdownItem::getCount).sum();

        if (lowData) {
            actionMsg = "Tiếp tục thu thập dữ liệu trước khi đưa ra quyết định vận hành.";
            actionLevel = "info";
        } else if (interactionSummary.getTotalInteractions() == 0) {
            actionMsg = "Khuyến khích người dùng đăng bài, bình luận hoặc phản ứng.";
            actionLevel = "warning";
        } else if (postsPct > 0 && postsPct < 25.0 && (commentsCount + reactionsCount) > postsCount) {
            actionMsg = String.format("Bài đăng chỉ %.1f%% — nên khuyến khích người dùng tạo nội dung.", postsPct);
            actionLevel = "warning";
        } else if (dauSummary.getConsecutiveDauDropDays() >= 3) {
            actionMsg = "Kiểm tra push notification, nội dung mới và lỗi hệ thống để phục hồi DAU.";
            actionLevel = "danger";
        } else if (intGrowth != null && intGrowth <= -30.0) {
            actionMsg = "Rà soát lỗi hệ thống và nội dung mới, cân nhắc push notification.";
            actionLevel = "danger";
        } else if (avg > 0 && peak >= avg * 2.0) {
            actionMsg = "Xem xét nội dung/sự kiện ngày đỉnh để nhân rộng mô hình thành công.";
            actionLevel = "info";
        } else if (top != null && top.getPercentage() >= 40.0 && !"Bài đăng".equals(top.getType())) {
            actionMsg = String.format("Tạo thêm nội dung gợi ý — %s đang chiếm %d%% tổng tương tác.", top.getType(), top.getPercentage());
            actionLevel = "info";
        } else if (intGrowth != null && intGrowth > 20.0) {
            actionMsg = "Duy trì chiến lược nội dung hiện tại và theo dõi ngày đỉnh.";
            actionLevel = "success";
        } else {
            actionMsg = "Tiếp tục theo dõi chỉ số — chưa cần can thiệp khẩn.";
            actionLevel = "success";
        }

        insights.add(AutoGeneratedInsightDto.builder()
                .id("action")
                .message("Đề xuất: " + actionMsg)
                .level(actionLevel)
                .severityLabel(getSeverityLabel(actionLevel))
                .build());

        return insights;
    }

    private String getSeverityLabel(String level) {
        switch (level) {
            case "success": return "tốt";
            case "warning": return "cần chú ý";
            case "danger": return "cảnh báo";
            case "info":
            default: return "thông tin";
        }
    }
}
