package project.kconnecta.admin.backend.feature.stats.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AutoGeneratedInsightDto {
    private String id;
    private String message;
    private String level;          // success, warning, danger, info
    private String severityLabel;  // tốt, cần chú ý, cảnh báo, thông tin
}
